import { MyText, Place } from "./lib.slint";

export component SecondaryTag inherits Rectangle {
    width: 296px;
    height: 128px;
    background: white;

    in property <[Place]> broken: [
      { place: "Berlin-Wannsee", elevators: ["Gleis 1/2 (S-Bahn)"] },
      { place: "Potsdamer Platz", elevators: ["EG -> Mittelpassarelle", "EG -> Mittelpassarelle"] },
      { place: "Potsdamer Platz", elevators: ["EG -> Mittelpassarelle", "EG -> Mittelpassarelle"] },
    ];
    in property <string> last_update: "18.11. - 16:20";

    VerticalLayout {
      spacing: -2px;

      header := HorizontalLayout {
          padding-left: 5px;
          padding-right: 5px;

          width: parent.width;
          height: self.preferred-height;
          padding: 2px;

          MyText {
            text: "ElStatus";
          }
          spacer := Rectangle { background: transparent; }
          MyText {
            text: last-update;
          }
      }

      line := Rectangle {
        width: parent.width;
        height: 2px;

        background: black;
      }

      VerticalLayout {
        width: parent.width;
        padding-top: 3px;
        padding-left: 5px;
        alignment: LayoutAlignment.start;

        for place in broken: VerticalLayout {
          spacing: -2px;
          alignment: LayoutAlignment.start;

          MyText {
            color: red;
            font-size: 14px;
            vertical-alignment: TextVerticalAlignment.center;
            horizontal-alignment: TextHorizontalAlignment.left;
            text: place.place;
          }

          for elevator in place.elevators: MyText {
            x: 10px;
            vertical-alignment: TextVerticalAlignment.center;
            horizontal-alignment: TextHorizontalAlignment.left;
            text: elevator;
          }
        }

      }
    }

}
